# Generated by Django 3.1.14 on 2025-01-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20250118_2349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pockemon',
            new_name='Pokemon',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='pockemon',
            new_name='pokemon',
        ),
    ]
