# Generated by Django 3.1.14 on 2025-02-03 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_auto_20250202_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='картинка покемона'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='previous_evolutions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolution', to='pokemon_entities.pokemon', verbose_name='предыдущая эволюция'),
        ),
    ]
