# Generated by Django 3.1.14 on 2025-02-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20250203_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(max_length=100, verbose_name='имя на русском'), verbose_name='картинка покемона'),
        ),
    ]
