# Generated by Django 3.1.14 on 2025-01-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_auto_20250119_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(max_length=100)),
        ),
    ]
